Updated Validation
Liu-group/AutoSolvate pull request #44
Opened 2024-03-22 20:11 UTC by nxtloveev3

Updated validation steps for solute charge and spin multiplicity.

2024-03-23 04:09 UTC, ffangliu requested changes

2024-03-23 04:09 UTC, ffangliu commented on autosolvate/autosolvate.py
> +            mult_suggest = (abs(slu_netcharge) + 1) % 2
This line doesn't make sense... The slu_netcharge is not the number of unpaired electrons. The number of unpaired electrons should be calculated as (total_electron_assuming_neural + netcharge)%2. 
Say, CH3, assuming neural, has 6+3=9 electrons. If the user provides a net charge of -1, then the actual total number of electrons is 9+1 = 10. Then, the # unpaired electron is 10%2 = 0. The spin multiplicity is 2*0+1 = 1.

You can verify for the CH3 (net charge -1), the implementation above is not correct and have multi_suggest = 0.

Pybel can count the number of electrons based on the input xyz file.

2024-03-23 04:09 UTC, ffangliu commented
@nxtloveev3 
There are still bugs in the pull request.

2024-03-23 17:42 UTC, nxtloveev3 commented
The new version is updated and tested using CH3 radical, CH3-, Naphthalene_neutral, and Naphthalene_radical. All of them passed the tests.

2024-03-26 20:38 UTC, ffangliu commented on autosolvate/autosolvate.py
> +    long_options = ["help", "main","solutename", "solvent", "output", "charge", "cubesize", "chargemethod", "spinmultiplicity", "srunuse","qmprogram","qmexe", "qmdir", "amberhome", "closeness","solve
Why did you change `r` to `r:`? Is the option `srunuse` now taking in an argument? The column symbol indicates whether it is something that requires an argument following that option.

2024-03-26 20:53 UTC, ffangliu approved these changes

2024-03-26 20:53 UTC, ffangliu commented on autosolvate/autosolvate.py
> +                slu_spinmult = (total_electrons - slu_netcharge) % 2 + 1
Does this modification overwrite the slu_spinmult provided by the user?

2024-03-26 20:53 UTC, merged